use sys;
CREATE TABLE tata_lash(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(255) NOT NULL,
TELEFONE_CLIENTE varchar(11) NOT NULL,
DATA_AGENDAMENTO DATETIME NOT NULL
);

INSERT NOME_CLIENTE, TELEFONE_CLIENTE, DATA_AGENDAMENTO