use sys;
CREATE TABLE tata_lash(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME_CLIENTE VARCHAR(255) NOT NULL,
TELEFONE_CLIENTE varchar(11) NOT NULL,
DATA_AGENDAMENTO DATETIME NOT NULL
);

INSERT INTO tata_lash (NOME_CLIENTE, TELEFONE_CLIENTE, DATA_AGENDAMENTO)
VALUES ("Camila Silva", "11954391234", "2026-04-19")